package base;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import java.sql.*;
import org.apache.commons.dbutils.DbUtils;

/**
 * Servlet implementation class SetupDatabase
 */
public class DBCon extends HttpServlet {
	private static final long serialVersionUID = 1L;
	
	private String db_path = "jdbc:hsqldb:file:${user.home}/i377/Team01d/db;shutdown=true"; 

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		response.getWriter().println("Loading data...");

		try {
			createTables();
			response.getWriter().println("Success!");
		} catch (Exception e) {
			System.out.println(e);
			throw new RuntimeException(e);
		}
	}

	@Override
	public void init() throws ServletException {
		try {
			Class.forName("org.hsqldb.jdbcDriver");
		} catch(Exception e) {
			throw new RuntimeException(e);
		}
	}

	private void createTables() throws Exception {	
		Connection conn = DriverManager.getConnection(db_path);

		Statement stmt = null;
		try {
			stmt = conn.createStatement();
			stmt.executeUpdate("DROP SCHEMA PUBLIC CASCADE");
			
			stmt.executeUpdate("create table  RIIGI_ADMIN_YKSUSE_LIIK ( "
				+ "riigi_admin_yksuse_lik_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,"
				+ "kood                     VARCHAR(10) NOT NULL,"
				+ "nimetus                  VARCHAR(100) NOT NULL,"
				+ "kommentaar                LONGVARCHAR,"
				+ "alates	                DATE NOT NULL,"
				+ "kuni	                    DATE NOT NULL,"
				+ "avaja	                VARCHAR(32) NOT NULL,"
				+ "avatud					DATE NOT NULL,"
				+ "muutuja	                VARCHAR(32) NOT NULL,"
				+ "muudetud		            DATE NOT NULL,"
				+ "sulgeja	                VARCHAR(32),"
				+ "suletud	 	            DATE NOT NULL,"
				+ "PRIMARY KEY (riigi_admin_yksuse_lik_id ),"
				+ ")");
			
			String std = "'1900-01-01', '2999-12-31', 'Admin', '2012-12-01', 'Admin', '2012-12-01', 'Admin', '2999-12-31'";
			String std1 = "'Admin', '2012-12-01', 'Admin', '2012-12-01', 'Admin', '2999-12-31'";  
			stmt.executeUpdate("insert into RIIGI_ADMIN_YKSUSE_LIIK "
					+ "(kood, nimetus, kommentaar, alates, kuni, avaja, avatud, muutuja, muudetud, sulgeja, suletud) VALUES "
					+ "('R', 'Riik', '', "	+ std + ")," + 
					 "('M', 'Maakond', '', " + std + ")," + 
					 "('L', 'Linn', '', " + std + ")," + 
					 "('V', 'Vald', '', " + std + ")," + 
					 "('A', 'Alev', '', " + std + ")," + 
					"('K', 'Kyla', '', " + std + ")" + 
					"");
			
	
			stmt.executeUpdate("CREATE TABLE  VOIMALIK_ALLUVUS (" 
				+ "voimalik_alluvus_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,"
				+ "riigi_admin_yksuse_lik		INTEGER,"
				+ "voimalik_alluv_lik_id		INTEGER,"
				+ "kommentaar                   LONGVARCHAR,"
				+ "avaja	                 	VARCHAR(32) NOT NULL,"
				+ "avatud                   	DATE NOT NULL,"
				+ "muutuja                 		VARCHAR(32) NOT NULL,"
				+ "muudetud               		DATE NOT NULL,"
				+ "sulgeja                		VARCHAR(32) NOT NULL,"
				+ "suletud              		DATE NOT NULL,"
				+ "PRIMARY KEY (voimalik_alluvus_id),"
				+ "FOREIGN KEY (riigi_admin_yksuse_lik) REFERENCES RIIGI_ADMIN_YKSUSE_LIIK ON DELETE RESTRICT,"
				+ "FOREIGN KEY (voimalik_alluv_lik_id) REFERENCES RIIGI_ADMIN_YKSUSE_LIIK ON DELETE RESTRICT"
				+ ")");
			stmt.executeUpdate("insert into VOIMALIK_ALLUVUS "
					+ "(riigi_admin_yksuse_lik, voimalik_alluv_lik_id, kommentaar,avaja, avatud, muutuja, muudetud, sulgeja, suletud) VALUES "+
	// @formatter:off
					"('1', '2', 'riik->maakond', " + std1 + ")," +
					"('2', '3', 'maakond->Linn', " + std1 + ")," +
					"('2', '4', 'maakond->vald', " + std1 + ")," +
					"('4', '5', 'vald->alev', " + std1 + ")," + 
					"('4', '6', 'vald->kyla', " + std1 + ")" +
	
					"");
			
		
			stmt.executeUpdate("create table RIIGI_ADMIN_YKSUS ( "
				+ "riigi_admin_yksus_id		INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,"
				+ "kood                     VARCHAR(20) NOT NULL,"
				+ "nimetus                  VARCHAR(100) NOT NULL,"
				+ "komentaar                LONGVARCHAR,"
				+ "riigi_admin_yksyse_liik_id	INTEGER NOT NULL,"
				+ "alates	                DATE NOT NULL,"
				+ "kuni		                DATE NOT NULL,"
				+ "avaja	                VARCHAR(32) NOT NULL,"
				+ "avatud	                DATE NOT NULL,"
				+ "muutuja	                VARCHAR(32) NOT NULL,"
				+ "muudetud		            DATE NOT NULL,"
				+ "sulgeja	                VARCHAR(32),"
				+ "suletud	                DATE NOT NULL,"
				+ "PRIMARY KEY (riigi_admin_yksus_id),"
				+ "FOREIGN KEY (riigi_admin_yksyse_liik_id) REFERENCES RIIGI_ADMIN_YKSUSE_LIIK ON DELETE RESTRICT"
				+ ")");

			stmt.executeUpdate("insert into RIIGI_ADMIN_YKSUS "
					+ "(kood, nimetus, komentaar, riigi_admin_yksyse_liik_id, alates, kuni, avaja, avatud, muutuja, muudetud, sulgeja, suletud) VALUES "
					+
	
					"('Eesti', 'Eesti Vabariik', '', '1'," + std + ")," + 
					"('Laanemaa', 'Laanemaa maakond', '', '2'," + std + ")," +
					"('Haapsalu', 'Haapsalu', '', '3'," + std + ")," + 
					"('RidalaVald', 'Ridala vald', '', '4'," + std + ")," + 
					"('RidalaAlev', 'Ridala alev', '', '5'," + std + ")," + 
					"('Taebla', 'Taebla kyla', '', '6'," + std + ")," + 
					"('Kiltsi', 'Kiltsi kyla', '', '6'," + std + ")," + 
					"('Uuemoisa', 'Uuemoisa kyla', '', '6'," + std + ")" +
					
					"");

			
			
			
			stmt.executeUpdate("create table ADMIN_ALLUV ( "
				+ "admin_alluvus_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,"
				+ "ylemus_yksus_id			INTEGER,"
				+ "alluv_yksus_id			INTEGER,"
				+ "Comment                  LONGVARCHAR,"
				+ "alates	                DATE NOT NULL,"
				+ "kuni	                    DATE NOT NULL,"
				+ "avaja	                VARCHAR(32) NOT NULL,"
				+ "avatud	                DATE NOT NULL,"
				+ "muutuja	                VARCHAR(32) NOT NULL,"
				+ "muudetud	                DATE NOT NULL,"
				+ "sulgeja	                VARCHAR(32),"
				+ "suletud	                DATE NOT NULL,"
				+ "PRIMARY KEY (admin_alluvus_id),"
				+ "FOREIGN KEY (ylemus_yksus_id) REFERENCES RIIGI_ADMIN_YKSUS ON DELETE RESTRICT,"
				+ "FOREIGN KEY (alluv_yksus_id) REFERENCES RIIGI_ADMIN_YKSUS ON DELETE RESTRICT"
				+ ")");
			stmt.executeUpdate("insert into ADMIN_ALLUV "
					+ "(ylemus_yksus_id, alluv_yksus_id, Comment, alates, kuni, avaja, avatud, muutuja, muudetud, sulgeja, suletud) VALUES "
					+

					"('1', '2', 'Eesti->Laanemaa'," + std + ")," + 
					"('2', '3', 'Laanemaa->Tallinn'," + std + ")," + 
					"('2', '4', 'Laanemaa->RidalaVald'," + std + ")," + 
					"('4', '5', 'RidalaVald->RidalaAlev'," + std + ")," + 
					"('4', '6', 'RidalaVald->Kiltsi'," + std + ")," + 
					"('4', '6', 'RidalaVald->Uuemoisa'," + std + ")," + 
					"('4', '6', 'RidalaVald->Taebla'," + std + ")" + 
					
					"");
		} finally {
			DbUtils.closeQuietly(stmt);
			DbUtils.closeQuietly(conn);
		}
	}

}
